name: dependabot-sync
on:
  schedule:
    - cron: "0 0 * * 0" # 每周日午夜
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-sync:
    uses: purpose168/meta-cn/.github/workflows/dependabot-sync.yml@main
    with:
      repo_name: ${{ github.event.repository.name }}
    secrets:
      gh_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
